name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [ "main" ]

permissions:
  # Actions의 GITHUB_TOKEN이 이 레포지토리에 push(쓰기)할 수 있도록 권한 부여
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build and deploy to GitHub Pages
        run: |
          mkdocs build
          mkdocs gh-deploy --force
